name: Tag New Version

on:
  push:
    branches:
      - main

jobs:
  call-bump-version-workflow:
    # For first-time setup, create a v0.0.0 tag as shown here:
    # https://github.com/ASFHyP3/actions#reusable-bump-versionyml
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.20.0
    permissions: {}
    with:
      user: username_for_github_actions
      email: email_for@github_actions.com
    secrets:
      USER_TOKEN: ${{ secrets.USERNAME_FOR_GITHUB_ACTIONS_PAK }}
